# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 25
:max_retries: 3

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [async_database_migration, 1]
  - [low, 2]
  - [scheduled_jobs, 2]
  - [webhooks, 2]
  - [bots, 2]
  - [active_storage_analysis, 2]
  - [action_mailbox_incineration, 2]
  - [active_storage_purge, 2]
  - [integrations, 3]
  - [default, 3]
  - [mailers, 3]
  - [medium, 4]
  - [events, 4]
  - [action_mailbox_routing, 4]
  - [high, 5]
  - [critical, 10]

# you can override concurrency based on environment
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
staging:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
